import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Demo numbers table
  numbers: defineTable({
    value: v.number(),
  }),

  // Authenticated users (from Clerk)
  users: defineTable({
    clerkId: v.string(),
    email: v.string(),
    name: v.string(),
    resumeText: v.optional(v.string()),
    identity: v.optional(
      v.object({
        headline: v.string(),
        skills: v.array(v.string()),
        interests: v.array(v.string()),
        goals: v.array(v.string()),
        lastUpdated: v.number(),
      })
    ),
    identityVersion: v.number(),
    createdAt: v.number(),
  }).index("by_clerk_id", ["clerkId"]),

  // Visitor profiles (evolving identity)
  visitors: defineTable({
    odentifier: v.string(), // visitorId from localStorage or clerkId
    name: v.optional(v.string()),
    email: v.optional(v.string()),
    
    // Self-declared identity (from resume/profile)
    declaredSkills: v.optional(v.array(v.string())),
    declaredInterests: v.optional(v.array(v.string())),
    
    // AI-perceived identity (from conversations)
    perceivedSkills: v.optional(v.array(v.string())),
    perceivedInterests: v.optional(v.array(v.string())),
    perceivedStrengths: v.optional(v.array(v.string())),
    
    // Aggregated metrics for recommendations
    totalInteractions: v.number(),
    positiveInteractionRate: v.number(), // 0-1
    topTags: v.optional(v.array(v.string())), // Most frequent tags
    identityVersion: v.number(),
    
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_identifier", ["odentifier"]),

  // Booths/People at the event
  booths: defineTable({
    name: v.string(),
    company: v.string(),
    description: v.string(),
    tags: v.array(v.string()), // What they're looking for / offering
    lookingFor: v.optional(v.array(v.string())), // Skills they want
    offering: v.optional(v.array(v.string())), // What they provide (jobs, mentorship, etc.)
    createdAt: v.number(),
  })
    .index("by_company", ["company"])
    .searchIndex("search_booths", {
      searchField: "description",
      filterFields: ["company"],
    }),

  // Rich interactions with LLM-processed data
  interactions: defineTable({
    visitorId: v.string(),
    visitorBoothId: v.string(),
    boothName: v.string(),

    // Raw content
    transcript: v.optional(v.string()),
    notes: v.optional(v.string()),

    // LLM-processed fields
    summary: v.optional(v.string()),
    tags: v.optional(v.array(v.string())),
    sentiment: v.optional(v.string()),
    confidence: v.optional(v.number()),
    keyTopics: v.optional(v.array(v.string())),
    actionItems: v.optional(v.array(v.string())),
    
    // New: Recommendation-relevant fields
    mentionedSkills: v.optional(v.array(v.string())),
    mentionedInterests: v.optional(v.array(v.string())),
    connectionPotential: v.optional(v.string()), // high/medium/low
    suggestedFollowUp: v.optional(v.string()),

    // Metadata
    hasAudio: v.boolean(),
    transcriptSource: v.string(),
    recordingDurationSec: v.number(),
    processingStatus: v.string(),
    llmModel: v.optional(v.string()),

    createdAt: v.number(),
  })
    .index("by_visitor", ["visitorId"])
    .index("by_booth", ["visitorBoothId"])
    .index("by_visitor_time", ["visitorId", "createdAt"]),

  // Recommendations generated by AI
  recommendations: defineTable({
    visitorId: v.string(),
    recommendedBoothId: v.string(),
    recommendedBoothName: v.string(),
    
    // Why this recommendation
    matchScore: v.number(), // 0-100
    matchReasons: v.array(v.string()),
    basedOnTags: v.array(v.string()),
    basedOnInteractions: v.array(v.id("interactions")),
    
    // Status
    status: v.string(), // "pending" | "clicked" | "visited" | "dismissed"
    
    createdAt: v.number(),
    updatedAt: v.optional(v.number()),
  })
    .index("by_visitor", ["visitorId"])
    .index("by_visitor_status", ["visitorId", "status"]),

  // Identity evolution snapshots (for "you arrived as X, leaving as Y")
  identitySnapshots: defineTable({
    visitorId: v.string(),
    timestamp: v.number(),
    trigger: v.string(),
    interactionId: v.optional(v.id("interactions")),

    // Snapshot of identity at this point
    skills: v.array(v.string()),
    interests: v.array(v.string()),
    perceivedTags: v.array(v.string()),
    interactionCount: v.number(),
    version: v.number(),
  }).index("by_visitor_time", ["visitorId", "timestamp"]),
});